In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os, sys
code_path = os.path.abspath('../code')

# Add the path to sys.path
if code_path not in sys.path:
    sys.path.append(code_path)

In [3]:
from week7 import particle
import numpy as np
from matplotlib import pyplot as plt

In [4]:
np.random.seed(43)
control = np.rint(np.random.uniform(low=-1, high=1, size=20))

In [5]:
my_particle = particle()

In [6]:
r_traj = np.zeros((2, len(control)+1))
for t, ft in enumerate(control):
    r_traj[:, t+1] = my_particle.T(r_traj[:, t], ft)

In [7]:
e_traj = np.zeros((2, 2*len(control)+1))
e_sig = np.zeros((2, 2, 2*len(control)+1))
K = my_particle.kf_gain()
                                
for t, ft in enumerate(control):
    if t == 0:
        e_traj[:, t] = np.zeros(2)
        e_sig[:, :, t] = my_particle.R
        obs = my_particle.O(my_particle.T(r_traj[:, t], ft))
        e_traj[:, t+1], e_sig[:, :, t+1] = my_particle.dynamic_update(e_traj[:, t], e_sig[:, :, t], ft)
    else:
        obs = my_particle.O(r_traj[:, t])
        e_traj[:, 2*t], e_sig[:, :, 2*t] = my_particle.measurement_update(e_traj[:, 2*t-1], e_sig[:, :, 2*t-1], K, obs)
        e_traj[:, 2*t+1], e_sig[:, :, 2*t+1] = my_particle.dynamic_update(e_traj[:, 2*t], e_sig[:, :, 2*t], ft)

In [8]:
e_traj

array([[  0.        ,   0.        ,   0.04613821,  -0.83232382,
         -0.23085464,  -0.61071391,  -0.93597983,  -2.44601457,
         -3.03761197,  -5.70412627,  -4.92667794,  -7.18254054,
         -7.14600764,  -8.39110058,  -7.74773896,  -8.63355011,
         -8.40332547,  -9.32603305,  -9.85189733, -12.12846416,
        -11.87925049, -14.1217098 , -13.6818421 , -15.75521362,
        -16.75433744, -18.4465473 , -18.42274911, -20.31982004,
        -20.44437391, -23.56642898, -22.79098531, -24.60854311,
        -25.0082922 , -27.88120219, -27.92551371, -30.7681979 ,
        -31.09043825, -34.19141308, -34.58723307, -38.95772394,
          0.        ],
       [  0.        ,  -1.        ,  -0.87846203,  -0.87846203,
         -0.37985927,  -1.37985927,  -1.51003474,  -2.51003474,
         -2.6665143 ,  -2.6665143 ,  -2.25586259,  -1.25586259,
         -1.24509294,  -1.24509294,  -0.88581115,  -0.88581115,
         -0.92270758,  -1.92270758,  -2.27656683,  -2.27656683,
         -2.24245

In [12]:
r_traj

array([[  0.        ,   0.        ,  -0.8441279 ,  -1.07631198,
         -2.63953561,  -5.19831924,  -7.05180122,  -7.88806631,
         -8.75847785,  -9.50400895, -11.69475022, -13.92922062,
        -16.28596306, -18.29004559, -20.50884903, -23.34147008,
        -24.91221343, -27.67109828, -30.63739507, -34.01452275,
        -38.48286323],
       [  0.        ,  -0.8441279 ,  -0.23218408,  -1.56322363,
         -2.55878362,  -1.85348198,  -0.83626509,  -0.87041154,
         -0.7455311 ,  -2.19074127,  -2.2344704 ,  -2.35674244,
         -2.00408253,  -2.21880344,  -2.83262104,  -1.57074335,
         -2.75888485,  -2.96629679,  -3.37712768,  -4.46834048,
         -3.8091078 ]])

In [10]:
e_sig[:, :, 2]

array([[-0.00352167, -0.10723995],
       [ 0.01715293,  0.07188883]])

In [11]:
control

array([-1.,  0., -1., -1., -0.,  1.,  0.,  0., -1.,  0., -0.,  1., -0.,
       -1.,  1., -1., -0., -0., -1.,  1.])